// Generated by GitHub Copilot
import { defineConfig } from "vitest/config";

// Generated by GitHub Copilot
export default defineConfig({
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.js"],
    include: ["src/**/*.test.{js,jsx}"]
  }
});
