# Generated by GitHub Copilot
"""Generate synthetic inference load for mlops-sentinel demo and alert testing."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import random
import time
from urllib import error, request


# Generated by GitHub Copilot
def build_parser() -> argparse.ArgumentParser:
    """Build and return argument parser for synthetic load generation."""

    parser = argparse.ArgumentParser(description="Generate synthetic inference events for mlops-sentinel")
    parser.add_argument("--base-url", default="http://127.0.0.1:8000", help="Backend base URL")
    parser.add_argument("--model-name", default="risk-model-v1", help="Model name for generated events")
    parser.add_argument("--events", type=int, default=120, help="Number of events to send")
    parser.add_argument("--sleep-ms", type=int, default=50, help="Delay between events in milliseconds")
    parser.add_argument(
        "--drift-ratio",
        type=float,
        default=0.3,
        help="Fraction of events generated with low confidence to simulate drift",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducible generation")
    parser.add_argument("--api-key", default="", help="Optional API key for protected endpoint")
    return parser


# Generated by GitHub Copilot
def build_event(model_name: str, low_confidence: bool) -> dict[str, object]:
    """Create one synthetic inference event payload."""

    if low_confidence:
        confidence = round(random.uniform(0.2, 0.5), 4)
        latency_ms = round(random.uniform(700, 1400), 2)
        prediction = random.choice(["review", "fallback", "manual"])
    else:
        confidence = round(random.uniform(0.65, 0.98), 4)
        latency_ms = round(random.uniform(40, 320), 2)
        prediction = random.choice(["approved", "accepted", "auto"])

    return {
        "model_name": model_name,
        "latency_ms": latency_ms,
        "prediction": prediction,
        "confidence": confidence,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "metadata": {
            "source": "demo-load-generator",
            "low_confidence": low_confidence,
        },
    }


# Generated by GitHub Copilot
def send_event(base_url: str, payload: dict[str, object], api_key: str) -> bool:
    """Send one event to POST /log and return True on accepted response."""

    endpoint = base_url.rstrip("/") + "/log"
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["X-API-Key"] = api_key

    req = request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST",
    )

    try:
        with request.urlopen(req, timeout=15) as response:
            return 200 <= response.status < 300
    except error.HTTPError as exc:
        print(f"HTTP error {exc.code}: {exc.reason}")
        return False
    except error.URLError as exc:
        print(f"Connection error: {exc.reason}")
        return False


# Generated by GitHub Copilot
def main() -> int:
    """Run synthetic load generation and print outcome summary."""

    args = build_parser().parse_args()

    if args.events <= 0:
        raise ValueError("--events must be a positive integer")
    if args.sleep_ms < 0:
        raise ValueError("--sleep-ms must be zero or positive")
    if args.drift_ratio < 0.0 or args.drift_ratio > 1.0:
        raise ValueError("--drift-ratio must be between 0 and 1")

    random.seed(args.seed)

    sent = 0
    failed = 0
    low_confidence_events = 0

    for index in range(args.events):
        low_confidence = random.random() < args.drift_ratio
        if low_confidence:
            low_confidence_events += 1

        payload = build_event(args.model_name, low_confidence=low_confidence)
        ok = send_event(args.base_url, payload, api_key=args.api_key)
        if ok:
            sent += 1
        else:
            failed += 1

        if args.sleep_ms > 0 and index < args.events - 1:
            time.sleep(args.sleep_ms / 1000.0)

    print(
        json.dumps(
            {
                "base_url": args.base_url,
                "model_name": args.model_name,
                "requested_events": args.events,
                "sent": sent,
                "failed": failed,
                "low_confidence_events": low_confidence_events,
                "drift_ratio": args.drift_ratio,
            },
            indent=2,
        )
    )

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
