
"""Integration tests for mlops-sentinel FastAPI endpoints."""

import json
from dataclasses import replace
from datetime import datetime, timezone

from fastapi.testclient import TestClient
import pytest

from app import main as main_module
from app.main import app, rate_limiter, storage

client = TestClient(app)


def _override_settings(monkeypatch, **changes):
    """Apply temporary runtime setting overrides for endpoint security tests."""

    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, **changes))


# Generated by GitHub Copilot
def _assert_error_contract(
    response,
    expected_status: int,
    expected_code: str,
    expected_message: str | None = None,
    expect_details: bool = False,
) -> None:
    """Validate normalized API error envelope fields for contract checks."""
    assert response.status_code == expected_status
    payload = response.json()
    assert isinstance(payload.get("error"), dict)
    assert payload["error"]["code"] == expected_code
    assert isinstance(payload["error"]["message"], str)
    if expected_message is not None:
        assert payload["error"]["message"] == expected_message
    assert isinstance(payload["error"]["request_id"], str)
    assert payload["error"]["request_id"]
    if expect_details:
        assert "details" in payload["error"]


@pytest.fixture(autouse=True)
def reset_storage(monkeypatch):
    """Clear persisted logs between tests for deterministic assertions."""

    rate_limiter.clear()
    _override_settings(monkeypatch, api_key="", rate_limit_per_minute=600)

    with storage._connect() as connection:  # pylint: disable=protected-access
        connection.execute("DELETE FROM inference_logs")
        connection.commit()

    yield

    with storage._connect() as connection:  # pylint: disable=protected-access
        connection.execute("DELETE FROM inference_logs")
        connection.commit()

    rate_limiter.clear()


def test_health_endpoint_reports_backend_status():
    """Health endpoint should return uptime-safe diagnostics."""

    response = client.get("/health")
    assert response.status_code == 200

    payload = response.json()
    assert payload["status"] in {"ok", "degraded"}
    assert "db_available" in payload
    assert "total_logs" in payload


def test_readiness_endpoint_reports_dependency_state():
    """Readiness endpoint should expose dependency status for orchestrator probes."""

    response = client.get("/ready")
    assert response.status_code == 200

    payload = response.json()
    assert payload["status"] == "ready"
    assert payload["db_available"] is True


def test_probe_alias_endpoints_match_primary_probes():
    """Compatibility aliases should mirror canonical probe responses."""

    health_alias = client.get("/healthz")
    assert health_alias.status_code == 200
    assert health_alias.json()["status"] in {"ok", "degraded"}

    ready_alias = client.get("/readyz")
    assert ready_alias.status_code == 200
    assert ready_alias.json()["status"] in {"ready", "not_ready"}


def test_log_ingest_and_summary_flow():
    """Posting a log should reflect in summary output and aggregates."""

    timestamp = datetime.now(timezone.utc).isoformat()
    response = client.post(
        "/log",
        json={
            "model_name": "risk-model-v1",
            "latency_ms": 123.4,
            "prediction": "approved",
            "confidence": 0.82,
            "timestamp": timestamp,
            "metadata": {"tenant": "demo"},
        },
    )

    assert response.status_code == 200
    ingest_payload = response.json()
    assert ingest_payload["status"] == "accepted"
    assert ingest_payload["log_id"] > 0

    summary_response = client.get("/summary?limit=10")
    assert summary_response.status_code == 200

    summary_payload = summary_response.json()
    assert summary_payload["total_items"] == 1
    assert len(summary_payload["items"]) == 1
    assert summary_payload["prediction_distribution"]["approved"] == 1


def test_export_csv_returns_expected_content_type():
    """CSV export endpoint should return attachment metadata and CSV body."""

    timestamp = datetime.now(timezone.utc).isoformat()
    client.post(
        "/log",
        json={
            "model_name": "risk-model-v1",
            "latency_ms": 44.2,
            "prediction": "review",
            "confidence": 0.45,
            "timestamp": timestamp,
        },
    )

    response = client.get("/export?format=csv&limit=10")
    assert response.status_code == 200
    assert response.headers["content-type"].startswith("text/csv")
    assert "model_name,latency_ms,prediction,confidence,timestamp" in response.text


def test_pipeline_handshake_ingest_summary_metrics_and_export_json():
    """Pipeline should expose consistent state across ingestion, summary, metrics, and export APIs."""

    model_name = "risk-model-handshake"

    for confidence in [0.41, 0.44, 0.49]:
        response = client.post(
            "/log",
            json={
                "model_name": model_name,
                "latency_ms": 980.0,
                "prediction": "review",
                "confidence": confidence,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "metadata": {"scenario": "pipeline-handshake"},
            },
        )
        assert response.status_code == 200
        assert response.json()["status"] == "accepted"

    summary_response = client.get(f"/summary?limit=10&model_name={model_name}")
    assert summary_response.status_code == 200
    summary_payload = summary_response.json()
    assert summary_payload["total_items"] == 3
    assert summary_payload["drift_flag"] is True
    assert summary_payload["prediction_distribution"]["review"] == 3

    metrics_response = client.get("/metrics")
    assert metrics_response.status_code == 200
    assert "inference_latency_ms" in metrics_response.text
    assert "inference_drift_flag" in metrics_response.text

    export_response = client.get(f"/export?format=json&limit=10&model_name={model_name}")
    assert export_response.status_code == 200
    export_payload = json.loads(export_response.text)
    assert len(export_payload["items"]) == 3
    assert export_payload["items"][0]["model_name"] == model_name


def test_log_requires_api_key_when_configured(monkeypatch):
    """Log endpoint should enforce API key when runtime key is configured."""

    _override_settings(monkeypatch, api_key="secret-key")

    unauthorized = client.post(
        "/log",
        json={
            "model_name": "risk-model-v1",
            "latency_ms": 11.0,
            "prediction": "approved",
            "confidence": 0.91,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    )
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.post(
        "/log",
        headers={"X-API-Key": "secret-key"},
        json={
            "model_name": "risk-model-v1",
            "latency_ms": 11.0,
            "prediction": "approved",
            "confidence": 0.91,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    )
    assert authorized.status_code == 200


def test_phase1_auth_required_contract(monkeypatch):
    """Require API key on protected routes and return normalized unauthorized payloads."""
    _override_settings(monkeypatch, api_key="phase1-secret")

    unauthorized = client.get("/summary")
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    invalid_key = client.get("/summary", headers={"X-API-Key": "wrong"})
    _assert_error_contract(
        invalid_key,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.get("/summary", headers={"X-API-Key": "phase1-secret"})
    assert authorized.status_code == 200


def test_phase1_error_contract_response():
    """Return normalized validation payloads with details for invalid query constraints."""
    response = client.get("/export?format=xml")
    _assert_error_contract(
        response,
        expected_status=422,
        expected_code="validation_error",
        expected_message="request_validation_failed",
        expect_details=True,
    )


def test_error_responses_include_request_and_security_headers(monkeypatch):
    """Unauthorized responses should preserve request correlation and hardened headers."""

    _override_settings(monkeypatch, api_key="phase1-secret")
    response = client.get("/summary")
    assert response.status_code == 401
    assert response.headers.get("X-Request-ID")
    assert response.headers.get("X-Content-Type-Options") == "nosniff"
    assert response.headers.get("X-Frame-Options") == "DENY"


def test_health_is_public_when_api_key_enabled(monkeypatch):
    """Health endpoint should remain public for readiness probes."""

    _override_settings(monkeypatch, api_key="secret-key")

    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] in {"ok", "degraded"}


def test_log_rate_limit_returns_429(monkeypatch):
    """Log endpoint should return 429 once per-client quota is exceeded."""

    _override_settings(monkeypatch, rate_limit_per_minute=1)

    first = client.post(
        "/log",
        json={
            "model_name": "risk-model-v1",
            "latency_ms": 13.0,
            "prediction": "approved",
            "confidence": 0.88,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    )
    assert first.status_code == 200

    second = client.post(
        "/log",
        json={
            "model_name": "risk-model-v1",
            "latency_ms": 14.0,
            "prediction": "approved",
            "confidence": 0.87,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    )
    _assert_error_contract(
        second,
        expected_status=429,
        expected_code="rate_limited",
        expected_message="rate_limited",
    )
    assert second.headers.get("Retry-After") == "60"
