# Generated by GitHub Copilot
"""Runtime configuration for mlops-sentinel backend service."""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import os


@dataclass(frozen=True)
class Settings:
    """Represents backend configuration loaded from environment variables."""

    app_name: str
    app_version: str
    db_path: str
    cors_origins: list[str]
    summary_size: int
    drift_confidence_threshold: float
    rate_limit_per_minute: int


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Load settings from environment variables with safe defaults."""

    app_name = os.getenv("MLOPS_APP_NAME", "mlops-sentinel")
    app_version = os.getenv("MLOPS_APP_VERSION", "0.2.0")
    db_path = os.getenv("MLOPS_DB_PATH", "./data/sentinel.db")

    origin_value = os.getenv(
        "MLOPS_CORS_ORIGINS",
        "http://127.0.0.1:4173,http://localhost:4173",
    )
    cors_origins = [origin.strip() for origin in origin_value.split(",") if origin.strip()]

    summary_size = int(os.getenv("MLOPS_SUMMARY_SIZE", "100"))
    drift_confidence_threshold = float(os.getenv("MLOPS_DRIFT_THRESHOLD", "0.55"))
    rate_limit_per_minute = int(os.getenv("MLOPS_RATE_LIMIT_PER_MINUTE", "600"))

    return Settings(
        app_name=app_name,
        app_version=app_version,
        db_path=db_path,
        cors_origins=cors_origins,
        summary_size=summary_size,
        drift_confidence_threshold=drift_confidence_threshold,
        rate_limit_per_minute=rate_limit_per_minute,
    )
