# Generated by GitHub Copilot
"""FastAPI service for model inference observability."""

from __future__ import annotations

from collections import deque
from statistics import mean

from fastapi import FastAPI
from fastapi.responses import PlainTextResponse
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest

from .models import InferenceLog, SummaryResponse

app = FastAPI(title="mlops-sentinel", version="0.1.0")

MAX_LOGS = 5000
SUMMARY_SIZE = 100
DRIFT_CONFIDENCE_THRESHOLD = 0.55

logs: deque[InferenceLog] = deque(maxlen=MAX_LOGS)

LATENCY_HISTOGRAM = Histogram(
    "inference_latency_ms",
    "Observed model inference latency in milliseconds",
    buckets=(10, 25, 50, 100, 250, 500, 1000, 2000),
)
PREDICTION_COUNTER = Counter(
    "inference_prediction_total",
    "Prediction class distribution",
    labelnames=("prediction",),
)
CONFIDENCE_HISTOGRAM = Histogram(
    "inference_confidence",
    "Model confidence distribution",
    buckets=(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
)
DRIFT_GAUGE = Gauge("inference_drift_flag", "Drift indicator derived from rolling confidence")


@app.get("/health")
def health() -> dict[str, str]:
    """Return a basic health status for service checks."""

    return {"status": "ok"}


@app.post("/log")
def ingest_log(payload: InferenceLog) -> dict[str, str]:
    """Ingest one inference log event and update in-memory metrics."""

    logs.append(payload)
    LATENCY_HISTOGRAM.observe(payload.latency_ms)
    PREDICTION_COUNTER.labels(prediction=payload.prediction).inc()
    CONFIDENCE_HISTOGRAM.observe(payload.confidence)

    recent_window = list(logs)[-SUMMARY_SIZE:]
    avg_confidence = mean(item.confidence for item in recent_window) if recent_window else 1.0
    DRIFT_GAUGE.set(1.0 if avg_confidence < DRIFT_CONFIDENCE_THRESHOLD else 0.0)

    return {"status": "accepted"}


@app.get("/summary", response_model=SummaryResponse)
def summary() -> SummaryResponse:
    """Return last 100 logs and current drift flag for dashboard display."""

    items = list(logs)[-SUMMARY_SIZE:]
    drift_flag = False
    if items:
        drift_flag = mean(item.confidence for item in items) < DRIFT_CONFIDENCE_THRESHOLD
    return SummaryResponse(items=items, drift_flag=drift_flag)


@app.get("/metrics")
def metrics() -> PlainTextResponse:
    """Expose Prometheus metrics from the observability service."""

    return PlainTextResponse(generate_latest(), media_type=CONTENT_TYPE_LATEST)
