
"""FastAPI service for model inference observability."""

from __future__ import annotations

from collections import Counter as PredictionCounter
from datetime import datetime, timezone
import json
from statistics import mean
from time import perf_counter
from typing import Annotated
from uuid import uuid4

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from fastapi.responses import JSONResponse, PlainTextResponse, Response
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest
from starlette.exceptions import HTTPException as StarletteHTTPException

from .config import get_settings
from .models import InferenceLog, SummaryResponse
from .rate_limit import InMemoryRateLimiter
from .storage import LogStorage

settings = get_settings()
storage = LogStorage(settings.db_path)
rate_limiter = InMemoryRateLimiter(window_seconds=60)
AUTH_EXEMPT_PATHS = {
    "/",
    "/health",
    "/ready",
    "/healthz",
    "/readyz",
    "/docs",
    "/openapi.json",
    "/redoc",
    "/metrics",
}

REQUEST_COUNTER = Counter(
    "http_requests_total",
    "HTTP request count",
    labelnames=("method", "endpoint", "status"),
)
REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds",
    labelnames=("method", "endpoint"),
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5),
)

LATENCY_HISTOGRAM = Histogram(
    "inference_latency_ms",
    "Observed model inference latency in milliseconds",
    labelnames=("model_name",),
    buckets=(10, 25, 50, 100, 250, 500, 1000, 2000),
)
CLASS_COUNTER = Counter(
    "inference_prediction_total",
    "Prediction class distribution",
    labelnames=("model_name", "prediction"),
)
CONFIDENCE_HISTOGRAM = Histogram(
    "inference_confidence",
    "Model confidence distribution",
    labelnames=("model_name",),
    buckets=(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
)
DRIFT_GAUGE = Gauge(
    "inference_drift_flag",
    "Drift indicator derived from rolling confidence",
    labelnames=("model_name",),
)


def _apply_standard_security_headers(response: Response) -> None:
    """Apply response headers that reduce common browser-side attack vectors."""

    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
    response.headers["Content-Security-Policy"] = "default-src 'none'; frame-ancestors 'none'; base-uri 'none'"
    if settings.enable_hsts:
        response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"


# Generated by GitHub Copilot
def _request_id_from_request(request: Request) -> str:
    """Read request correlation id from state or fallback headers."""
    request_id = getattr(request.state, "request_id", None)
    if isinstance(request_id, str) and request_id:
        return request_id
    return request.headers.get("X-Request-ID", "unknown")


# Generated by GitHub Copilot
def _build_error_payload(
    request: Request,
    code: str,
    message: str,
    details: object | None = None,
) -> dict[str, object]:
    """Build normalized error payloads for API failures."""
    payload: dict[str, object] = {
        "error": {
            "code": code,
            "message": message,
            "request_id": _request_id_from_request(request),
        }
    }
    if details is not None:
        payload["error"]["details"] = details
    return payload


# Generated by GitHub Copilot
def _status_to_error_code(status_code: int) -> str:
    """Map HTTP statuses to stable error contract codes."""
    mapping = {
        400: "bad_request",
        401: "unauthorized",
        403: "forbidden",
        404: "not_found",
        409: "conflict",
        413: "payload_too_large",
        422: "validation_error",
        429: "rate_limited",
    }
    if status_code >= 500:
        return "internal_error"
    return mapping.get(status_code, "request_failed")


def _require_api_key(
    request: Request,
    x_api_key: Annotated[str | None, Header(alias="X-API-Key")] = None,
) -> None:
    """Enforce optional API key auth for non-probe endpoints."""

    if request.method == "OPTIONS" or request.url.path in AUTH_EXEMPT_PATHS:
        return
    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="api_key_invalid")


app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
    dependencies=[Depends(_require_api_key)],
)

app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.allowed_hosts)
app.add_middleware(GZipMiddleware, minimum_size=settings.gzip_minimum_size)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_context_middleware(request: Request, call_next):
    """Attach request id, security headers, and HTTP-level metrics for each request."""

    request_id = request.headers.get("X-Request-ID", str(uuid4()))
    request.state.request_id = request_id
    start = perf_counter()
    response: Response | None = None

    try:
        if request.method in {"POST", "PUT", "PATCH"}:
            raw_content_length = request.headers.get("content-length", "").strip()
            if raw_content_length:
                try:
                    content_length = int(raw_content_length)
                except ValueError:
                    response = JSONResponse(
                        status_code=400,
                        content=_build_error_payload(
                            request=request,
                            code="bad_request",
                            message="invalid_content_length_header",
                        ),
                    )
                else:
                    if content_length > settings.max_payload_bytes:
                        response = JSONResponse(
                            status_code=413,
                            content=_build_error_payload(
                                request=request,
                                code="payload_too_large",
                                message="payload_too_large",
                            ),
                        )

        if response is None:
            response = await call_next(request)
    except Exception:
        REQUEST_COUNTER.labels(
            method=request.method,
            endpoint=request.url.path,
            status="500",
        ).inc()
        raise
    finally:
        elapsed = perf_counter() - start
        REQUEST_LATENCY.labels(method=request.method, endpoint=request.url.path).observe(elapsed)

    REQUEST_COUNTER.labels(method=request.method, endpoint=request.url.path, status=str(response.status_code)).inc()

    response.headers["X-Request-ID"] = request_id
    _apply_standard_security_headers(response)
    return response


# Generated by GitHub Copilot
@app.exception_handler(StarletteHTTPException)
@app.exception_handler(HTTPException)
async def handle_http_exception(request: Request, exc: HTTPException) -> JSONResponse:
    """Return normalized payloads for expected HTTP failures."""
    message = str(exc.detail) if exc.detail is not None else "request_failed"
    return JSONResponse(
        status_code=exc.status_code,
        content=_build_error_payload(
            request=request,
            code=_status_to_error_code(exc.status_code),
            message=message,
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(RequestValidationError)
async def handle_validation_exception(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Return normalized payloads for validation failures."""
    return JSONResponse(
        status_code=422,
        content=_build_error_payload(
            request=request,
            code="validation_error",
            message="request_validation_failed",
            details=exc.errors(),
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(Exception)
async def handle_unexpected_exception(request: Request, _: Exception) -> JSONResponse:
    """Return normalized payloads for unhandled internal errors."""
    return JSONResponse(
        status_code=500,
        content=_build_error_payload(
            request=request,
            code="internal_error",
            message="internal_server_error",
        ),
    )


@app.get("/health")
def health() -> dict[str, object]:
    """Return backend health details for deployment and uptime checks."""

    db_available = storage.is_available()
    return {
        "status": "ok" if db_available else "degraded",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "db_path": storage.db_path,
        "db_available": db_available,
        "total_logs": storage.count_logs(),
    }


@app.get("/ready")
def readiness() -> JSONResponse:
    """Return readiness probe response with HTTP 503 when dependencies are unavailable."""

    db_available = storage.is_available()
    payload = {
        "status": "ready" if db_available else "not_ready",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "db_available": db_available,
    }
    return JSONResponse(status_code=200 if db_available else 503, content=payload)


# Generated by GitHub Copilot
@app.get("/healthz", include_in_schema=False)
def healthz() -> dict[str, object]:
    """Compatibility alias for health probes expecting /healthz."""
    return health()


# Generated by GitHub Copilot
@app.get("/readyz", include_in_schema=False)
def readyz() -> JSONResponse:
    """Compatibility alias for readiness probes expecting /readyz."""
    return readiness()


@app.post("/log")
def ingest_log(payload: InferenceLog, request: Request) -> dict[str, object]:
    """Ingest one inference log event and update metrics/detection state."""

    client_key = request.client.host if request.client else "unknown"
    if not rate_limiter.allow(client_key, settings.rate_limit_per_minute):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")

    log_id = storage.insert_log(payload)

    LATENCY_HISTOGRAM.labels(model_name=payload.model_name).observe(payload.latency_ms)
    CLASS_COUNTER.labels(model_name=payload.model_name, prediction=payload.prediction).inc()
    CONFIDENCE_HISTOGRAM.labels(model_name=payload.model_name).observe(payload.confidence)

    model_logs = storage.get_logs(limit=settings.summary_size, model_name=payload.model_name)
    avg_conf = mean(item.confidence for item in model_logs) if model_logs else 1.0
    DRIFT_GAUGE.labels(model_name=payload.model_name).set(
        1.0 if avg_conf < settings.drift_confidence_threshold else 0.0
    )

    return {
        "status": "accepted",
        "log_id": log_id,
        "drift_flag": avg_conf < settings.drift_confidence_threshold,
    }


@app.get("/summary", response_model=SummaryResponse)
def summary(
    limit: int = Query(default=settings.summary_size, ge=1, le=500),
    model_name: str | None = Query(default=None),
) -> SummaryResponse:
    """Return recent log slice and drift signal for dashboard clients."""

    items = storage.get_logs(limit=limit, model_name=model_name)
    avg_conf = mean(item.confidence for item in items) if items else None
    drift_flag = bool(avg_conf is not None and avg_conf < settings.drift_confidence_threshold)

    distribution_counter = PredictionCounter(item.prediction for item in items)
    prediction_distribution = dict(distribution_counter)

    return SummaryResponse(
        items=items,
        drift_flag=drift_flag,
        avg_confidence=avg_conf,
        total_items=storage.count_logs(model_name=model_name),
        prediction_distribution=prediction_distribution,
        drift_threshold=settings.drift_confidence_threshold,
    )


@app.get("/export")
def export_logs(
    format: str = Query(default="json", pattern="^(json|csv)$"),
    limit: int = Query(default=1000, ge=1, le=5000),
    model_name: str | None = Query(default=None),
) -> Response:
    """Export recent logs in JSON or CSV for offline analysis."""

    items = storage.get_logs(limit=limit, model_name=model_name)

    if format == "json":
        payload = {
            "items": [
                {
                    "model_name": item.model_name,
                    "latency_ms": item.latency_ms,
                    "prediction": item.prediction,
                    "confidence": item.confidence,
                    "timestamp": item.timestamp.isoformat(),
                    "metadata": item.metadata,
                }
                for item in items
            ]
        }
        return Response(
            content=json.dumps(payload, ensure_ascii=True),
            media_type="application/json",
            headers={"Content-Disposition": "attachment; filename=mlops-sentinel-export.json"},
        )

    csv_lines = ["model_name,latency_ms,prediction,confidence,timestamp"]
    for item in items:
        csv_lines.append(
            f"{item.model_name},{item.latency_ms},{item.prediction},{item.confidence},{item.timestamp.isoformat()}"
        )

    return Response(
        content="\n".join(csv_lines),
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=mlops-sentinel-export.csv"},
    )


@app.get("/metrics")
def metrics() -> PlainTextResponse:
    """Expose Prometheus metrics for scraping."""

    return PlainTextResponse(generate_latest(), media_type=CONTENT_TYPE_LATEST)
