# Generated by GitHub Copilot
"""Pydantic models used by the monitoring API."""

from datetime import datetime

from pydantic import BaseModel, Field


class InferenceLog(BaseModel):
    """Represents one model inference event entering observability pipeline."""

    model_name: str = Field(min_length=1, max_length=120)
    latency_ms: float = Field(ge=0)
    prediction: str = Field(min_length=1, max_length=120)
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp: datetime


class SummaryResponse(BaseModel):
    """Response model for returning sampled recent logs."""

    items: list[InferenceLog]
    drift_flag: bool
