# Generated by GitHub Copilot
"""Pydantic models used by the monitoring API."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field, field_validator


class InferenceLog(BaseModel):
    """Represents one model inference event entering observability pipeline."""

    model_name: str = Field(min_length=1, max_length=120)
    latency_ms: float = Field(ge=0)
    prediction: str = Field(min_length=1, max_length=120)
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] | None = None

    @field_validator("timestamp")
    @classmethod
    def validate_timestamp_timezone(cls, value: datetime) -> datetime:
        """Ensure timestamp is timezone aware for deterministic time operations."""

        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)


class SummaryResponse(BaseModel):
    """Response model for returning sampled recent logs and aggregate context."""

    items: list[InferenceLog]
    drift_flag: bool
    avg_confidence: float | None
    total_items: int
    prediction_distribution: dict[str, int]
    drift_threshold: float
