// Generated by GitHub Copilot
import { useEffect, useMemo, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";

function App() {
  const [items, setItems] = useState([]);
  const [driftFlag, setDriftFlag] = useState(false);

  useEffect(() => {
    let active = true;

    async function loadSummary() {
      try {
        const response = await fetch(`${API_BASE_URL}/summary`);
        if (!response.ok) {
          throw new Error(`Summary request failed: ${response.status}`);
        }
        const payload = await response.json();
        if (active) {
          setItems(payload.items || []);
          setDriftFlag(Boolean(payload.drift_flag));
        }
      } catch (error) {
        console.error(error);
      }
    }

    loadSummary();
    const interval = setInterval(loadSummary, 5000);

    return () => {
      active = false;
      clearInterval(interval);
    };
  }, []);

  const latencyData = useMemo(
    () =>
      items.slice(-30).map((item, index) => ({
        index,
        latency_ms: item.latency_ms,
      })),
    [items]
  );

  const predictionCounts = useMemo(() => {
    const counter = new Map();
    for (const item of items) {
      counter.set(item.prediction, (counter.get(item.prediction) || 0) + 1);
    }
    return Array.from(counter.entries()).map(([prediction, count]) => ({ prediction, count }));
  }, [items]);

  return (
    <main style={{ fontFamily: "Segoe UI, sans-serif", padding: 24 }}>
      <h1 style={{ marginBottom: 4 }}>mlops-sentinel</h1>
      <p style={{ marginTop: 0, marginBottom: 16 }}>
        Real-time latency and prediction distribution monitoring.
      </p>

      {driftFlag && (
        <div
          role="alert"
          style={{
            marginBottom: 16,
            border: "1px solid #d32f2f",
            background: "#fdeaea",
            color: "#7f1d1d",
            padding: 12,
            borderRadius: 8,
          }}
        >
          Drift alert: rolling confidence dropped below threshold.
        </div>
      )}

      <section style={{ marginBottom: 24 }}>
        <h2 style={{ marginBottom: 8 }}>Latency</h2>
        <div style={{ width: "100%", height: 280 }}>
          <ResponsiveContainer>
            <LineChart data={latencyData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="index" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Line type="monotone" dataKey="latency_ms" stroke="#1976d2" dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </section>

      <section>
        <h2 style={{ marginBottom: 8 }}>Prediction Distribution</h2>
        <div style={{ width: "100%", height: 280 }}>
          <ResponsiveContainer>
            <BarChart data={predictionCounts}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="prediction" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Bar dataKey="count" fill="#2e7d32" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </section>
    </main>
  );
}

export default App;
